name: coriolan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.2
  - blast=2.12.0
  - plotly=5.6.0
  - numpy=1.22.2
  - reportlab=3.5.68
  - muscle=3.8.1551
  - fasttree=2.1.11
